swagger: "2.0"
info:
  version: "0.0.1"
  title: TAMUHack-AA
# during dev, should point to your local machine
host: localhost:3030
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /reservation:
    x-swagger-router-controller: reservation
    get:
      description: Returns a reservation matching the specified record locator
      operationId: reservation
      parameters:
        - name: recordLocator
          in: query
          description: "6 character string for the desired reservation"
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ReservationResponse"
        "500":
            description: Reservation not found
            schema:
              type: string
  /flight:
    x-swagger-router-controller: flight
    get:
      description: Returns a flight matching the specified flight number
      operationId: flight
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/FlightSegment"
  /flights:
    x-swagger-router-controller: flight
    get:
      operationId: flights
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            type: array
            items: 
              $ref: "#/definitions/FlightSegment"
  /docs:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  ReservationResponse:
    required:
      - recordLocator
    properties:
      firstName:
        type: string
      lastName:
        type: string
      recordLocator:
        type: string        
      flights:
        type: array
        items:
          $ref: "#/definitions/FlightSegment"
  FlightSegment:
    properties:
      flightNumber: 
        type: string
      originCode: 
        type: string
      originCity:
        type: string
      destinationCode:
        type: string
      destinationCity:
        type: string
      estimatedDeparture:
        type: string
      scheduledDeparture:
        type: string
      estimatedArrival:
        type: string
      scheduledArrival:
        type: string
        